from __future__ import annotations
from pathlib import Path
from typing import Protocol, Mapping, Any


class ArtifactTransportPort(Protocol):
    def status(self) -> Mapping[str, Any]: ...
    def send_semantic_result(self, result: Mapping[str, Any], path: Path, *, priority: int = 0) -> Mapping[str, Any]: ...
    def send_map_delta(self, delta: Mapping[str, Any], path: Path, *, priority: int = 0) -> Mapping[str, Any]: ...
    def send_urgent_event(self, event: Mapping[str, Any], path: Path, *, priority: int = 0) -> Mapping[str, Any]: ...
    def send_map_preview(self, metadata: Mapping[str, Any], path: Path, *, priority: int = 0) -> Mapping[str, Any]: ...
